# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0001_initial'),
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('amount', models.FloatField(help_text='Credit and debit are represented by positive and negative value.', verbose_name='Amount')),
                ('reference_amount', models.FloatField(blank=True, editable=False, help_text='Value based on account curency.', null=True, verbose_name='Reference Amount')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('active', models.BooleanField(default=True, help_text='A disabled transaction will be save as a draft and not use in any report.', verbose_name='Enable')),
            ],
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('abstracttransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.AbstractTransaction')),
                ('new_amount', models.FloatField(help_text='Amount of cash in the new currency', verbose_name='New Amount')),
                ('new_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change', to='currency.Currency')),
            ],
            bases=('transactions.abstracttransaction',),
        ),
        migrations.CreateModel(
            name='DebitsCredits',
            fields=[
                ('abstracttransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.AbstractTransaction')),
            ],
            bases=('transactions.abstracttransaction',),
        ),
        migrations.AddField(
            model_name='abstracttransaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='abstracttransaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='categories.Category'),
        ),
        migrations.AddField(
            model_name='abstracttransaction',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='currency.Currency'),
        ),
    ]
