# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abstracttransaction',
            old_name='amount',
            new_name='local_amount',
        ),
        migrations.RenameField(
            model_name='abstracttransaction',
            old_name='currency',
            new_name='local_currency',
        ),
        migrations.RemoveField(
            model_name='abstracttransaction',
            name='reference_amount',
        ),
        migrations.AddField(
            model_name='debitscredits',
            name='foreign_amount',
            field=models.FloatField(blank=True, editable=False, help_text='Value based on account curency.', null=True, verbose_name='Reference Amount'),
        ),
        migrations.AddField(
            model_name='debitscredits',
            name='foreign_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='currency.Currency'),
        ),
    ]
