# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20161117_0224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='change',
            options={'verbose_name': 'Change', 'verbose_name_plural': 'Changes'},
        ),
        migrations.AlterModelOptions(
            name='debitscredits',
            options={'verbose_name': 'DebitsCredit', 'verbose_name_plural': 'DebitsCredits'},
        ),
        migrations.AddField(
            model_name='abstracttransaction',
            name='last_edited',
            field=models.DateTimeField(auto_now=True, verbose_name='Last edited'),
        ),
    ]
