# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-11 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '__first__'),
        ('transactions', '0004_auto_20170224_0334'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(help_text='Amount paid for this shared transaction', verbose_name='Amount')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Attendee')),
            ],
        ),
        migrations.AddField(
            model_name='debitscredits',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='events.Event'),
        ),
        migrations.AddField(
            model_name='debitscredits',
            name='used_by',
            field=models.ManyToManyField(help_text='Attendee who used this transaction for shared payment.', to='events.Attendee'),
        ),
        migrations.AddField(
            model_name='paidby',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.DebitsCredits'),
        ),
    ]
