# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-11 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20170224_0334'),
    ]

    operations = [

    ]