# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-15 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20170811_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidby',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='events.Attendee'),
        ),
        migrations.AlterField(
            model_name='paidby',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='transactions.DebitsCredits'),
        ),
    ]
