# Generated by Django 2.1 on 2018-09-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20171015_0312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paidby',
            name='attendee',
        ),
        migrations.RemoveField(
            model_name='paidby',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='abstracttransaction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='abstracttransaction',
            name='date',
        ),
        migrations.RemoveField(
            model_name='abstracttransaction',
            name='local_amount',
        ),
        migrations.RemoveField(
            model_name='abstracttransaction',
            name='local_currency',
        ),
        migrations.RemoveField(
            model_name='abstracttransaction',
            name='name',
        ),
        migrations.RemoveField(
            model_name='change',
            name='new_amount',
        ),
        migrations.RemoveField(
            model_name='change',
            name='new_currency',
        ),
        migrations.RemoveField(
            model_name='debitscredits',
            name='event',
        ),
        migrations.RemoveField(
            model_name='debitscredits',
            name='used_by',
        ),
        migrations.AddField(
            model_name='abstracttransaction',
            name='blob',
            field=models.TextField(blank=True, verbose_name='blob'),
        ),
        migrations.DeleteModel(
            name='PaidBy',
        ),
    ]
