# Generated by Django 2.1 on 2018-09-13 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_auto_20180913_0941'),
        ('transactions', '0008_auto_20180913_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstracttransaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='categories.Category'),
        ),
    ]
