# Generated by Django 2.1 on 2019-03-19 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('paiment_method', models.CharField(choices=[('COUPON', 'Coupon'), ('STRIPE', 'Stripe')], max_length=20, verbose_name='Paiment method')),
                ('reference_id', models.CharField(max_length=128, verbose_name='Reference ID')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], max_length=20, verbose_name='Status')),
                ('comment', models.TextField(blank=True, help_text='Will give context to the user', null=True, verbose_name='Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: FALL25OFF', max_length=128, unique=True, verbose_name='id')),
                ('name', models.CharField(help_text='Max 128 characters', max_length=128, verbose_name='Name')),
                ('percent_off', models.IntegerField(default=0, help_text='between 0 and 100', verbose_name='Percentage off')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Valid until')),
                ('max_redemptions', models.IntegerField(verbose_name='Max redemptions')),
                ('affiliate_percent', models.IntegerField(default=0, help_text='between 0 and 100', verbose_name='Affiliate percent')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('affiliate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Currency')),
                ('duration', models.IntegerField(default=12, help_text='Per month', verbose_name='How many month to add')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Valid until')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
            ],
        ),
        migrations.AddField(
            model_name='charge',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='saas.Coupon'),
        ),
        migrations.AddField(
            model_name='charge',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='saas.Product'),
        ),
        migrations.AddField(
            model_name='charge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to=settings.AUTH_USER_MODEL),
        ),
    ]
