# Generated by Django 2.1 on 2019-04-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='reference_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Reference ID'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_redemptions',
            field=models.IntegerField(blank=True, null=True, verbose_name='Max redemptions'),
        ),
    ]
