# Generated by Django 2.2.10 on 2020-05-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0002_auto_20190421_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='stripe_session_id',
            field=models.TextField(default='', help_text='Generated by Stripe API', verbose_name='Stripe product id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stripe_product_id',
            field=models.TextField(default='', help_text='Looks like prod_HKHuxHWnp5SnIL', verbose_name='Stripe product id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='charge',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('PENDING', 'Pending'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], max_length=20, verbose_name='Status'),
        ),
    ]
