# Generated by Django 2.2.10 on 2020-05-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0003_auto_20200523_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stripe_product_id',
            field=models.CharField(help_text='Looks like prod_HKHuxHWnp5SnIL', max_length=128, verbose_name='Stripe product id'),
        ),
    ]
