# Generated by Django 2.2.10 on 2020-05-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0004_auto_20200523_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='stripe_session_id',
            field=models.CharField(help_text='Generated by Stripe API', max_length=128, verbose_name='Stripe product id'),
        ),
    ]
