# Generated by Django 4.2.7 on 2023-11-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0006_auto_20200705_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
    ]
