# Generated by Django 4.2.7 on 2023-11-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0007_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='coupon',
        ),
        migrations.AlterField(
            model_name='charge',
            name='paiment_method',
            field=models.CharField(choices=[('STRIPE', 'Stripe')], max_length=20, verbose_name='Paiment method'),
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
