# Generated by Django 4.2.7 on 2023-11-28 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0011_remove_product_currency_remove_product_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
