# Generated by Django 4.2.7 on 2023-11-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0012_remove_price_product_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripecustomer',
            old_name='stripeCustomerId',
            new_name='stripe_customer_id',
        ),
        migrations.RenameField(
            model_name='stripecustomer',
            old_name='stripeSubscriptionId',
            new_name='stripe_subscription_id',
        ),
        migrations.AlterField(
            model_name='price',
            name='stripe_price_id',
            field=models.CharField(help_text='Looks like price_*', max_length=128, verbose_name='Stripe price id'),
        ),
    ]
