# Generated by Django 4.2.7 on 2023-11-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0013_rename_stripecustomerid_stripecustomer_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
