# Generated by Django 4.2.7 on 2023-11-28 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0014_stripecustomer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='saas.price'),
        ),
        migrations.AlterField(
            model_name='price',
            name='stripe_price_id',
            field=models.CharField(help_text='Looks like price_*', max_length=128, unique=True, verbose_name='Stripe price id'),
        ),
    ]
