# Generated by Django 4.2.7 on 2023-11-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0015_stripecustomer_price_alter_price_stripe_price_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecustomer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
