# Generated by Django 4.2.7 on 2023-12-03 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saas', '0016_alter_stripecustomer_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(max_length=255)),
                ('trial_end', models.DateTimeField(null=True)),
                ('current_period_end', models.DateTimeField(null=True)),
                ('cancel_at', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='saas.price')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='stripe', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='StripeCustomer',
        ),
    ]
