# Generated by Django 4.2.7 on 2023-12-03 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saas', '0017_stripesubscription_delete_stripecustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripesubscription',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stripe', to=settings.AUTH_USER_MODEL),
        ),
    ]
