# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('sign', models.CharField(max_length=6, verbose_name='Sign')),
                ('space', models.BooleanField(default=True, verbose_name='Add a space between amount and sign')),
                ('after_amount', models.BooleanField(choices=[(False, 'Before the amount'), (True, 'After the amount')], default=True, verbose_name='Sign position')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Currency',
            },
        ),
    ]
