# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-25 04:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='favorite',
            field=models.ManyToManyField(related_name='favoritesCurrencies', to=settings.AUTH_USER_MODEL),
        ),
    ]
