# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-28 13:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20161128_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(max_length=256, unique=True, verbose_name='Token')),
                ('creationDate', models.DateField(auto_now_add=True, verbose_name='')),
            ],
            options={
                'ordering': ('creationDate', 'token'),
            },
        ),
        migrations.CreateModel(
            name='AllowAccountAccessToken',
            fields=[
                ('abstracttoken_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tokens.AbstractToken')),
                ('email', models.EmailField(max_length=254, verbose_name='User email')),
                ('permission', models.CharField(choices=[(b'A', b'Administration'), (b'W', b'Read/write'), (b'R', b'Read')], max_length=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('sendBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('tokens.abstracttoken',),
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('abstracttoken_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tokens.AbstractToken')),
                ('pourcentageUser', models.IntegerField(default=0, help_text='Pourcentage of discount for buyer', verbose_name='User pourcentage')),
                ('pourcentageAffiliate', models.IntegerField(default=0, help_text='Pourcentage credited to referee user', verbose_name='Affiliate pourcentage')),
                ('validUntil', models.DateField(blank=True, help_text='Until when can this token be used', null=True, verbose_name='Valid Until')),
                ('validCounter', models.IntegerField(blank=True, help_text='How many times can this token be used', null=True, verbose_name='How many use')),
                ('referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('tokens.abstracttoken',),
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('abstracttoken_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tokens.AbstractToken')),
                ('newEmail', models.EmailField(max_length=254, verbose_name='New email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('tokens.abstracttoken',),
        ),
    ]
