# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-03 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowaccountaccesstoken',
            name='permission',
            field=models.CharField(choices=[(b'W', b'Read/write'), (b'R', b'Read')], max_length=1),
        ),
    ]
