# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-11 04:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignedTermsAndConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, help_text='Date of publication', verbose_name='Creation date')),
                ('markdown', models.TextField(editable=False, help_text='Formatted in Markdown', verbose_name='Terms and conditions)')),
            ],
        ),
        migrations.AddField(
            model_name='signedtermsandconditions',
            name='terms',
            field=models.ForeignKey(help_text='Terms agreed with user', on_delete=django.db.models.deletion.CASCADE, to='terms.TermsAndConditions'),
        ),
        migrations.AddField(
            model_name='signedtermsandconditions',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
