# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-03 03:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currency', '0001_initial'),
        ('accounts', '0002_auto_20161128_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGuests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.CharField(choices=[(b'W', b'Read/write'), (b'R', b'Read')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='accountrules',
            name='account',
        ),
        migrations.RemoveField(
            model_name='accountrules',
            name='user',
        ),
        migrations.RemoveField(
            model_name='account',
            name='users',
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AccountRules',
        ),
        migrations.AddField(
            model_name='accountguests',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='accountguests',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='currency.Currency'),
        ),
        migrations.AddField(
            model_name='accountguests',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to=settings.AUTH_USER_MODEL),
        ),
    ]
