# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 03:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20161203_0300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('create', 'name'), 'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='accountguests',
            options={'ordering': ('account', 'user'), 'verbose_name': 'Guest', 'verbose_name_plural': 'Guests'},
        ),
        migrations.AddField(
            model_name='account',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Is public'),
        ),
        migrations.AlterField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountguests',
            name='permissions',
            field=models.CharField(choices=[('W', 'Read/write'), ('R', 'Read')], max_length=1),
        ),
    ]
