# Generated by Django 2.1.11 on 2019-10-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_currencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='preferences',
            field=models.TextField(blank=True, verbose_name='blob'),
        ),
    ]
