# Generated by Django 2.1 on 2019-01-07 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_auto_20170224_0334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blob', models.TextField(blank=True, verbose_name='blob')),
                ('last_edited', models.DateTimeField(auto_now=True, verbose_name='Last edited')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='accounts.Account')),
            ],
        ),
    ]
