# Generated by Django 2.1 on 2019-01-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='deleted',
            field=models.BooleanField(default=False, help_text='If true, this entry has been deleted and we keep this is as deleted as a tombstone.', verbose_name='Deleted'),
        ),
    ]
