# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_auto_20161203_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowaccountaccesstoken',
            name='permission',
            field=models.CharField(choices=[('W', 'Read/write'), ('R', 'Read')], max_length=1),
        ),
    ]
