# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-15 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0004_auto_20170815_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstracttoken',
            name='token',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=32, unique=True, verbose_name='Token'),
        ),
    ]
