# Generated by Django 2.1 on 2019-03-18 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0005_auto_20170815_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowaccountaccesstoken',
            name='abstracttoken_ptr',
        ),
        migrations.RemoveField(
            model_name='allowaccountaccesstoken',
            name='account',
        ),
        migrations.RemoveField(
            model_name='allowaccountaccesstoken',
            name='sendBy',
        ),
        migrations.RemoveField(
            model_name='discountcode',
            name='abstracttoken_ptr',
        ),
        migrations.RemoveField(
            model_name='discountcode',
            name='referee',
        ),
        migrations.DeleteModel(
            name='AllowAccountAccessToken',
        ),
        migrations.DeleteModel(
            name='DiscountCode',
        ),
    ]
