# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 04:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20170224_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
    ]
