# Generated by Django 2.1 on 2018-10-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_auto_20171015_0312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='category',
            name='selectable',
        ),
        migrations.AddField(
            model_name='category',
            name='blob',
            field=models.TextField(blank=True, verbose_name='blob'),
        ),
        migrations.AddField(
            model_name='category',
            name='deleted',
            field=models.BooleanField(default=True, help_text='If true, this entry has been deleted and we keep this is as deleted as a tombstone.', verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='category',
            name='last_edited',
            field=models.DateTimeField(auto_now=True, verbose_name='Last edited'),
        ),
    ]
