# Generated by Django 2.1 on 2019-03-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActiveUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2019, editable=False, verbose_name='Year')),
                ('month', models.IntegerField(default=3, editable=False, verbose_name='Month')),
                ('day', models.IntegerField(default=9, editable=False, verbose_name='Day')),
                ('counter', models.IntegerField(default=0, editable=False, verbose_name='Counter')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyActiveUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2019, editable=False, verbose_name='Year')),
                ('month', models.IntegerField(default=3, editable=False, verbose_name='Month')),
                ('counter', models.IntegerField(default=0, editable=False, verbose_name='Counter')),
            ],
        ),
    ]
