# Generated by Django 2.1.8 on 2019-05-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20190318_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactiveuser',
            name='day',
            field=models.IntegerField(default=15, editable=False, verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='dailyactiveuser',
            name='month',
            field=models.IntegerField(default=5, editable=False, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='monthlyactiveuser',
            name='month',
            field=models.IntegerField(default=5, editable=False, verbose_name='Month'),
        ),
    ]
