# Generated by Django 2.1.8 on 2019-05-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20190515_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactiveuser',
            name='day',
            field=models.IntegerField(default=20, editable=False, verbose_name='Day'),
        ),
    ]
