# Generated by Django 2.1.8 on 2019-07-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20190520_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactiveuser',
            name='day',
            field=models.IntegerField(default=6, editable=False, verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='dailyactiveuser',
            name='month',
            field=models.IntegerField(default=7, editable=False, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='monthlyactiveuser',
            name='month',
            field=models.IntegerField(default=7, editable=False, verbose_name='Month'),
        ),
    ]
