# Generated by Django 2.1.11 on 2019-09-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20190706_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactiveuser',
            name='day',
            field=models.IntegerField(default=26, editable=False, verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='dailyactiveuser',
            name='month',
            field=models.IntegerField(default=9, editable=False, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='monthlyactiveuser',
            name='month',
            field=models.IntegerField(default=9, editable=False, verbose_name='Month'),
        ),
    ]
