# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-11 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_auto_20170224_0334'),
        ('tokens', '0003_auto_20170224_0334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name='Fullname')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Name')),
                ('date_begin', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('date_end', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('archived', models.BooleanField(default=False, help_text='Archived events will be displayed with less priority.', verbose_name='Archive')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='EventToken',
            fields=[
                ('abstracttoken_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tokens.AbstractToken')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='events.Attendee')),
            ],
            bases=('tokens.abstracttoken',),
        ),
        migrations.AddField(
            model_name='attendee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='events.Event'),
        ),
    ]
