# Generated by Django 2.1 on 2018-09-17 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170811_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='account',
        ),
        migrations.RemoveField(
            model_name='eventtoken',
            name='abstracttoken_ptr',
        ),
        migrations.RemoveField(
            model_name='eventtoken',
            name='attendee',
        ),
        migrations.DeleteModel(
            name='Attendee',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventToken',
        ),
    ]
