# Generated by Django 2.1 on 2019-03-11 08:25

from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='valid_until',
            field=models.DateTimeField(default=timezone.now, help_text='On SASS, this is the validation date', verbose_name='Valid until'),
        ),
    ]