# Generated by Django 2.1 on 2019-03-18 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_profile_valid_until'),
    ]

    operations = [
    ]