# Generated by Django 2.1 on 2019-03-18 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_profile_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 17, 13, 39, 57, 725490), help_text='On SASS, this is the validation date', verbose_name='Valid until'),
        ),
    ]
