# Generated by Django 2.1 on 2019-03-18 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20190318_1339'),
    ]

    operations = [
    ]