# Generated by Django 2.1 on 2019-03-18 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20190318_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 17, 15, 40, 25, 60027), help_text='On SASS, this is the validation date', verbose_name='Valid until'),
        ),
    ]
