# Generated by Django 2.1.8 on 2019-05-15 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20190318_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.CharField(choices=[('NONE', 'None'), ('GRAVATAR', 'Gravatar')], default='NONE', help_text='Select between different origins.', max_length=20, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 14, 8, 56, 1, 998008), help_text='On SASS, this is the validation date', verbose_name='Valid until'),
        ),
    ]
