# Generated by Django 2.1.8 on 2019-05-20 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_auto_20190515_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 19, 9, 43, 36, 339948), help_text='On SASS, this is the validation date', verbose_name='Valid until'),
        ),
    ]
