# Generated by Django 2.1.8 on 2019-05-20 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_auto_20190515_0856'),
    ]

    operations = [
    ]