# Generated by Django 2.1.8 on 2019-07-06 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_auto_20190520_0943'),
    ]

    operations = [
    ]