# Generated by Django 2.1.8 on 2019-07-06 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_auto_20190520_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 5, 3, 59, 38, 528577), help_text='On SASS, this is the validation date', verbose_name='Valid until'),
        ),
    ]
