# Generated by Django 2.1.11 on 2019-10-09 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_auto_20190926_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='On SASS, this is the validation date', verbose_name='Valid until'),
        ),
    ]
