# Generated by Django 2.1.11 on 2019-10-09 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0009_auto_20191009_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='valid_until',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='On SASS, this is the validation date', verbose_name='Valid until'),
        ),
    ]
