# Generated by Django 2.2.10 on 2020-05-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0010_auto_20191009_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text="Generated by Stripe's API", max_length=128, null=True, verbose_name='Stripe costumer id'),
        ),
    ]
