# Generated by Django 4.1.8 on 2023-05-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0011_profile_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auto_sync',
            field=models.BooleanField(default=False, verbose_name='Auto sync in app'),
        ),
    ]
