# Generated by Django 4.1.8 on 2023-06-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0012_profile_auto_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='key_verified',
            field=models.BooleanField(default=False, help_text='Private key has been verified and saved by user', verbose_name='Key verified'),
        ),
    ]
