# Generated by Django 4.2.7 on 2023-11-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0013_profile_key_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='auto_sync',
            field=models.BooleanField(default=True, verbose_name='Auto sync in app'),
        ),
    ]
