# Generated by Django 4.2.7 on 2023-11-28 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0014_alter_profile_auto_sync'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='stripe_customer_id',
        ),
    ]
